const MONGOOSE_URI =
  "mongodb+srv://balajiaadi:Balaji100$good@aadeshcluster.vfqikmt.mongodb.net/?retryWrites=true&w=majority&appName=aadeshcluster";
const DB_NAME = "datamodelling";
const PORT = 8080;
const CORS_ORIGIN = "http://localhost:3000";
const ACCESS_TOKEN_SECRET =
  "jafjuoiefakdjfkakjfduifojkjfkljkjkjkjiorkjLJJHJHWJKHJKHJHLKJJIO2343U4UjiujkhjkhjkhiuhDJAHSFUOEQIWUROIUALCMVCNVMNCBVAFIUFRUFJROIEUW";
const ACCESS_TOKEN_EXPIRY = "1d";
const REFRESH_TOKEN_SECRET =
  "CkljdaksjoCAgfafjquieroiuwlKLJMJKHYUTTRGHJVBVJHYTYTUGHJGIUYUIYTUHJGHJGHGHJGGFYTFYTRYUTYUGFGYTTYGHJGBJHHGFTYYUGHVHGJHKJHLIUYUIYUTYUG";
const REFRESH_TOKEN_EXPIRY = "10d";
const CLOUDINARY_CLOUD_NAME = "aadesh2000";
const CLOUDINARY_API_KEY = 854891869758133;
const CLOUDINARY_API_SECRET = "5FT5t93oGbFFVoh4Bujv87yAZYQ";

export {
  MONGOOSE_URI,
  DB_NAME,
  PORT,
  CORS_ORIGIN,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
};
